<?php

namespace App;

use SleepingOwl\Admin\AssetManager\AssetManager;
use SleepingOwl\Admin\FormItems\MultiSelect;
use SleepingOwl\Admin\Interfaces\FormItemInterface;

class ColorMultipleSelect extends MultiSelect implements FormItemInterface
{
    protected $label;

    public function render()
    {
        AssetManager::addStyle('admin::default/css/multiple-select.css');
        AssetManager::addScript('admin::default/js/multiple-select.js');
        //$content = 
    }
    
    public function label($label = null)
    {
        $this->label = $label;
        return $this;
    }
    
    public function options($options = null)
    {
        return parent::options($options); // TODO: Change the autogenerated stub
    }
}
